export {default as Home} from './Home'
export {default as Explor} from './Explor'
export {default as Saved} from './Saved'
export {default as AllUsers} from './AllUsers'
export {default as CreatePost} from './CreatePost'
export {default as EditPost} from './EditPost'
export {default as PostDetails} from './PostDetails'
export {default as Profile} from './Profile'
export {default as UpdateProfile} from './UpdateProfile'
export {default as LikedPosts} from './LikedPosts'

